plugins {
    alias libs.plugins.android.application
    alias libs.plugins.jetbrains.kotlin.android
}

import org.jetbrains.kotlin.gradle.dsl.JvmTarget

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file("signing.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdk = 37

    defaultConfig {
        applicationId "com.example.kinginstaller"
        minSdk 26
        targetSdk 37
        versionCode 6
        versionName "1.9"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        aidl true
    }

    signingConfigs {
        config {
            storeFile file("keysing.jks")
            storePassword keystoreProperties['STORE_PASSWORD']
            keyAlias keystoreProperties['KEYSTORE_ALIAS']
            keyPassword keystoreProperties['KEY_PASSWORD']
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            signingConfig signingConfigs.config
        }
        release {
            minifyEnabled true
            signingConfig signingConfigs.config
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    namespace 'com.example.kinginstaller'

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "KingInstaller-v${variant.versionName}.apk"
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.core.ktx
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.hiddenapibypass

    def shizuku_version = '13.1.5'
    implementation libs.api
    implementation libs.provider

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}